# Generated by Django 4.1.7 on 2023-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.TextField(choices=[('LOSE WEIGHT', 'LOSE WEIGHT'), ('MUSCLE STRENGTH', 'MUSCLE STRENGTH'), ('MUSCLE MASS', 'MUSCLE MASS'), ('BODY DEFINITION', 'BODY DEFINITION'), ('CARDIO', 'CARDIO')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('kcal_rep', models.PositiveIntegerField()),
            ],
        ),
    ]
