# Generated by Django 4.1.7 on 2023-05-30 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='kcal_rep',
        ),
        migrations.AddField(
            model_name='goals',
            name='author',
            field=models.ForeignKey(default='kevin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
