# Generated by Django 4.1.7 on 2023-05-30 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0004_delete_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.TextField(choices=[('LOSE WEIGHT', 'LOSE WEIGHT'), ('MUSCLE STRENGTH', 'MUSCLE STRENGTH'), ('MUSCLE MASS', 'MUSCLE MASS'), ('BODY DEFINITION', 'BODY DEFINITION'), ('CARDIO', 'CARDIO')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_finish_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
