# Generated by Django 4.1.7 on 2023-05-30 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 14, 13, 13, 152020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goals',
            name='estimated_finish_date',
            field=models.DateField(),
        ),
    ]
