# Generated by Django 4.1.7 on 2023-05-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goals_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
