# Generated by Django 4.1.7 on 2023-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
