# Generated by Django 4.1.7 on 2023-05-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_alter_goals_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
