# Generated by Django 4.1.7 on 2023-06-01 21:54

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='status',
            field=models.TextField(default='Active'),
        ),
        migrations.AddConstraint(
            model_name='goals',
            constraint=models.CheckConstraint(check=models.Q(('estimated_finish_date__gte', django.db.models.functions.datetime.Now())), name='Estimated finish date must be greater than or equal today!'),
        ),
    ]
