# Generated by Django 4.1.7 on 2023-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_goals_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goals',
            name='Estimated finish date must be greater than or equal today!',
        ),
        migrations.AddConstraint(
            model_name='goals',
            constraint=models.CheckConstraint(check=models.Q(('estimated_finish_date__gt', models.F('creation_datetime'))), name='Estimated finish date must be greater than or equal today!'),
        ),
    ]
