# Generated by Django 4.1.7 on 2023-06-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_remove_goals_estimated finish date must be greater than or equal today!_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goals',
            name='Estimated finish date must be greater than or equal today!',
        ),
    ]
