# Generated by Django 4.1.7 on 2023-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_active_goals_customuser_completed_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(default='07/25/2001'),
            preserve_default=False,
        ),
    ]
