# Generated by Django 4.1.7 on 2023-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
