# Generated by Django 4.1.7 on 2023-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('muscle_group', models.IntegerField(choices=[('BACK', 1), ('SHOULDERS', 2), ('ABDOMEN', 3), ('CHEST', 4), ('LEGS', 5), ('ARMS', 6)])),
            ],
        ),
    ]
