# Generated by Django 4.1.7 on 2023-05-22 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises_list',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group',
            field=models.PositiveIntegerField(choices=[(1, 'BACK'), (2, 'SHOULDERS'), (3, 'ABDOMEN'), (4, 'CHEST'), (5, 'LEGS'), (6, 'ARMS')]),
        ),
    ]
