# Generated by Django 4.1.7 on 2023-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workout_exercises_list_workoutexercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercises',
            name='repetitions',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
