# Generated by Django 4.1.7 on 2023-05-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutexercises_repetitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='body',
            new_name='description',
        ),
    ]
