# Generated by Django 4.1.7 on 2023-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_rename_body_workout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
