# Generated by Django 4.1.7 on 2023-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workout_exercise_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group',
            field=models.TextField(choices=[('BACK', 'BACK'), ('SHOULDERS', 'SHOULDERS'), ('ABDOMEN', 'ABDOMEN'), ('CHEST', 'CHEST'), ('LEGS', 'LEGS'), ('ARMS', 'ARMS')]),
        ),
    ]
