# Generated by Django 4.1.7 on 2023-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_remove_workout_date_workout_last_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='kcal_rep',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
