# Generated by Django 4.1.7 on 2023-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_exercises_kcal_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercises',
            name='kcal_tot',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
