# Generated by Django 4.1.7 on 2023-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_workoutexercises_kcal_tot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='last_training_date',
            field=models.DateField(null=True),
        ),
    ]
