# Generated by Django 4.1.7 on 2023-06-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_workout_last_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='kcal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
