# Generated by Django 4.1.7 on 2023-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workout_kcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
